/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IOmniTokenCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bridgeMint"
      | "bridgeTransfer"
      | "bridgeTransferReceiver"
      | "fetchOmniTokenMintFee"
      | "fetchOmniTokenTransferFee"
      | "mint"
      | "simpleBridgeMint"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bridgeMint",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeTransfer",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeTransferReceiver",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchOmniTokenMintFee",
    values: [BigNumberish, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchOmniTokenTransferFee",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "simpleBridgeMint",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "bridgeMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bridgeTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgeTransferReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchOmniTokenMintFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchOmniTokenTransferFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "simpleBridgeMint",
    data: BytesLike
  ): Result;
}

export interface IOmniTokenCore extends BaseContract {
  connect(runner?: ContractRunner | null): IOmniTokenCore;
  waitForDeployment(): Promise<this>;

  interface: IOmniTokenCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bridgeMint: TypedContractMethod<
    [
      destChainId: BigNumberish,
      receiver: AddressLike,
      amount: BigNumberish,
      gasTip: BigNumberish
    ],
    [void],
    "payable"
  >;

  bridgeTransfer: TypedContractMethod<
    [destChainId: BigNumberish, receiver: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;

  bridgeTransferReceiver: TypedContractMethod<
    [toAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  fetchOmniTokenMintFee: TypedContractMethod<
    [
      value: BigNumberish,
      destChainId: BigNumberish,
      receiver: AddressLike,
      amount: BigNumberish
    ],
    [bigint],
    "view"
  >;

  fetchOmniTokenTransferFee: TypedContractMethod<
    [destChainId: BigNumberish, receiver: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;

  mint: TypedContractMethod<
    [toAddress: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;

  simpleBridgeMint: TypedContractMethod<
    [
      destChainId: BigNumberish,
      receiver: AddressLike,
      amount: BigNumberish,
      gasTip: BigNumberish
    ],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bridgeMint"
  ): TypedContractMethod<
    [
      destChainId: BigNumberish,
      receiver: AddressLike,
      amount: BigNumberish,
      gasTip: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "bridgeTransfer"
  ): TypedContractMethod<
    [destChainId: BigNumberish, receiver: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "bridgeTransferReceiver"
  ): TypedContractMethod<
    [toAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fetchOmniTokenMintFee"
  ): TypedContractMethod<
    [
      value: BigNumberish,
      destChainId: BigNumberish,
      receiver: AddressLike,
      amount: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fetchOmniTokenTransferFee"
  ): TypedContractMethod<
    [destChainId: BigNumberish, receiver: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [toAddress: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "simpleBridgeMint"
  ): TypedContractMethod<
    [
      destChainId: BigNumberish,
      receiver: AddressLike,
      amount: BigNumberish,
      gasTip: BigNumberish
    ],
    [void],
    "payable"
  >;

  filters: {};
}
