/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IColor,
  IColorInterface,
} from "../../../../../contracts/DApps/OmniTokenBridge/VizingTokenBridge.sol/IColor";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "companionMessage",
        type: "bytes",
      },
    ],
    name: "bridgeConvertTokenReceiver",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IColor__factory {
  static readonly abi = _abi;
  static createInterface(): IColorInterface {
    return new Interface(_abi) as IColorInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IColor {
    return new Contract(address, _abi, runner) as unknown as IColor;
  }
}
