/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TESTERC20UGV1__factory } from "./TESTERC20UGV1__factory";
export { TESTERC20UGV2__factory } from "./TESTERC20UGV2__factory";
