/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface ConverterInterface extends Interface {
  getFunction(
    nameOrSignature: "bridgeConvertTokenReceiver" | "revertTokenwithBridge"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bridgeConvertTokenReceiver",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revertTokenwithBridge",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      AddressLike,
      BytesLike,
      BytesLike,
      AddressLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "bridgeConvertTokenReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revertTokenwithBridge",
    data: BytesLike
  ): Result;
}

export interface Converter extends BaseContract {
  connect(runner?: ContractRunner | null): Converter;
  waitForDeployment(): Promise<this>;

  interface: ConverterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bridgeConvertTokenReceiver: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  revertTokenwithBridge: TypedContractMethod<
    [
      amount: BigNumberish,
      toAddress: AddressLike,
      destChainId: BigNumberish,
      token: AddressLike,
      permitData: BytesLike,
      companionMessage: BytesLike,
      bridge: AddressLike
    ],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bridgeConvertTokenReceiver"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "revertTokenwithBridge"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      toAddress: AddressLike,
      destChainId: BigNumberish,
      token: AddressLike,
      permitData: BytesLike,
      companionMessage: BytesLike,
      bridge: AddressLike
    ],
    [void],
    "payable"
  >;

  filters: {};
}
