/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface OmniTokenCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LandingPad"
      | "LaunchPad"
      | "PacketAdditionParams"
      | "PacketMessage"
      | "PacketMessages"
      | "allowance"
      | "approve"
      | "balanceOf"
      | "bridgeMint"
      | "bridgeTransfer"
      | "bridgeTransferHandler"
      | "bridgeTransferReceiver"
      | "computeTradeFee"
      | "decimals"
      | "defaultBridgeMode"
      | "emit2LaunchPad"
      | "estimateVizingGasFee"
      | "exactInput"
      | "exactOutput"
      | "fetchOmniTokenMintFee"
      | "fetchOmniTokenTransferFee"
      | "infoBackEmit"
      | "maxArrivalTime"
      | "maxGasLimit"
      | "minArrivalTime"
      | "minGasLimit"
      | "mint"
      | "mirrorToken"
      | "name"
      | "owner"
      | "receiveStandardMessage"
      | "renounceOwnership"
      | "selectedRelayer"
      | "setMirrorToken"
      | "simpleBridgeMint"
      | "symbol"
      | "tokenMintfee"
      | "tokenOnChain"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Approval" | "OwnershipTransferred" | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LandingPad",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "LaunchPad", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PacketAdditionParams",
    values: [BytesLike, BytesLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "PacketMessage",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "PacketMessages",
    values: [
      BytesLike[],
      AddressLike[],
      BigNumberish[],
      BigNumberish[],
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeMint",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeTransfer",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeTransferHandler",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeTransferReceiver",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "computeTradeFee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "defaultBridgeMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emit2LaunchPad",
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateVizingGasFee",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "exactInput",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exactOutput",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchOmniTokenMintFee",
    values: [BigNumberish, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchOmniTokenTransferFee",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "infoBackEmit",
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "maxArrivalTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxGasLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minArrivalTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minGasLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mirrorToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receiveStandardMessage",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "selectedRelayer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMirrorToken",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "simpleBridgeMint",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenMintfee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOnChain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "LandingPad", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "LaunchPad", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PacketAdditionParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PacketMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PacketMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bridgeMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bridgeTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgeTransferHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgeTransferReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeTradeFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultBridgeMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emit2LaunchPad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateVizingGasFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exactInput", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "exactOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchOmniTokenMintFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchOmniTokenTransferFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "infoBackEmit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxArrivalTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minArrivalTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mirrorToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveStandardMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "selectedRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMirrorToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "simpleBridgeMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenMintfee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOnChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OmniTokenCore extends BaseContract {
  connect(runner?: ContractRunner | null): OmniTokenCore;
  waitForDeployment(): Promise<this>;

  interface: OmniTokenCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LandingPad: TypedContractMethod<[], [string], "view">;

  LaunchPad: TypedContractMethod<[], [string], "view">;

  PacketAdditionParams: TypedContractMethod<
    [
      mode: BytesLike,
      tokenSymbol: BytesLike,
      sender: AddressLike,
      receiver: AddressLike,
      amount: BigNumberish
    ],
    [string],
    "view"
  >;

  PacketMessage: TypedContractMethod<
    [
      mode: BytesLike,
      targetContract: AddressLike,
      gasLimit: BigNumberish,
      price: BigNumberish,
      message: BytesLike
    ],
    [string],
    "view"
  >;

  PacketMessages: TypedContractMethod<
    [
      mode: BytesLike[],
      targetContract: AddressLike[],
      gasLimit: BigNumberish[],
      price: BigNumberish[],
      message: BytesLike[]
    ],
    [string[]],
    "view"
  >;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  bridgeMint: TypedContractMethod<
    [
      destChainId: BigNumberish,
      receiver: AddressLike,
      amount: BigNumberish,
      gasTip: BigNumberish
    ],
    [void],
    "payable"
  >;

  bridgeTransfer: TypedContractMethod<
    [destChainid: BigNumberish, receiver: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;

  bridgeTransferHandler: TypedContractMethod<
    [destChainid: BigNumberish, receiver: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;

  bridgeTransferReceiver: TypedContractMethod<
    [toAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  computeTradeFee: TypedContractMethod<
    [destChainid: BigNumberish, value: BigNumberish],
    [bigint],
    "view"
  >;

  decimals: TypedContractMethod<[], [bigint], "view">;

  defaultBridgeMode: TypedContractMethod<[], [string], "view">;

  emit2LaunchPad: TypedContractMethod<
    [
      earliestArrivalTimestamp: BigNumberish,
      latestArrivalTimestamp: BigNumberish,
      relayer: AddressLike,
      sender: AddressLike,
      value: BigNumberish,
      destChainid: BigNumberish,
      additionParams: BytesLike,
      message: BytesLike
    ],
    [void],
    "payable"
  >;

  estimateVizingGasFee: TypedContractMethod<
    [
      value: BigNumberish,
      destChainid: BigNumberish,
      additionParams: BytesLike,
      message: BytesLike
    ],
    [bigint],
    "view"
  >;

  exactInput: TypedContractMethod<
    [destChainid: BigNumberish, amountIn: BigNumberish],
    [bigint],
    "view"
  >;

  exactOutput: TypedContractMethod<
    [destChainid: BigNumberish, amountOut: BigNumberish],
    [bigint],
    "view"
  >;

  fetchOmniTokenMintFee: TypedContractMethod<
    [
      value: BigNumberish,
      destChainid: BigNumberish,
      receiver: AddressLike,
      amount: BigNumberish
    ],
    [bigint],
    "view"
  >;

  fetchOmniTokenTransferFee: TypedContractMethod<
    [destChainid: BigNumberish, receiver: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;

  infoBackEmit: TypedContractMethod<
    [
      earliestArrivalTimestamp: BigNumberish,
      latestArrivalTimestamp: BigNumberish,
      relayer: AddressLike,
      sender: AddressLike,
      value: BigNumberish,
      destChainid: BigNumberish,
      additionParams: BytesLike,
      message: BytesLike
    ],
    [void],
    "payable"
  >;

  maxArrivalTime: TypedContractMethod<[], [bigint], "view">;

  maxGasLimit: TypedContractMethod<[], [bigint], "view">;

  minArrivalTime: TypedContractMethod<[], [bigint], "view">;

  minGasLimit: TypedContractMethod<[], [bigint], "view">;

  mint: TypedContractMethod<
    [toAddress: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;

  mirrorToken: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  receiveStandardMessage: TypedContractMethod<
    [srcChainId: BigNumberish, srcContract: BigNumberish, message: BytesLike],
    [void],
    "payable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  selectedRelayer: TypedContractMethod<[], [string], "view">;

  setMirrorToken: TypedContractMethod<
    [Chainid: BigNumberish, tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  simpleBridgeMint: TypedContractMethod<
    [
      destChainId: BigNumberish,
      receiver: AddressLike,
      amount: BigNumberish,
      gasTip: BigNumberish
    ],
    [void],
    "payable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenMintfee: TypedContractMethod<[], [bigint], "view">;

  tokenOnChain: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LandingPad"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LaunchPad"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PacketAdditionParams"
  ): TypedContractMethod<
    [
      mode: BytesLike,
      tokenSymbol: BytesLike,
      sender: AddressLike,
      receiver: AddressLike,
      amount: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "PacketMessage"
  ): TypedContractMethod<
    [
      mode: BytesLike,
      targetContract: AddressLike,
      gasLimit: BigNumberish,
      price: BigNumberish,
      message: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "PacketMessages"
  ): TypedContractMethod<
    [
      mode: BytesLike[],
      targetContract: AddressLike[],
      gasLimit: BigNumberish[],
      price: BigNumberish[],
      message: BytesLike[]
    ],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "bridgeMint"
  ): TypedContractMethod<
    [
      destChainId: BigNumberish,
      receiver: AddressLike,
      amount: BigNumberish,
      gasTip: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "bridgeTransfer"
  ): TypedContractMethod<
    [destChainid: BigNumberish, receiver: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "bridgeTransferHandler"
  ): TypedContractMethod<
    [destChainid: BigNumberish, receiver: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "bridgeTransferReceiver"
  ): TypedContractMethod<
    [toAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "computeTradeFee"
  ): TypedContractMethod<
    [destChainid: BigNumberish, value: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "defaultBridgeMode"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "emit2LaunchPad"
  ): TypedContractMethod<
    [
      earliestArrivalTimestamp: BigNumberish,
      latestArrivalTimestamp: BigNumberish,
      relayer: AddressLike,
      sender: AddressLike,
      value: BigNumberish,
      destChainid: BigNumberish,
      additionParams: BytesLike,
      message: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "estimateVizingGasFee"
  ): TypedContractMethod<
    [
      value: BigNumberish,
      destChainid: BigNumberish,
      additionParams: BytesLike,
      message: BytesLike
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "exactInput"
  ): TypedContractMethod<
    [destChainid: BigNumberish, amountIn: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "exactOutput"
  ): TypedContractMethod<
    [destChainid: BigNumberish, amountOut: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fetchOmniTokenMintFee"
  ): TypedContractMethod<
    [
      value: BigNumberish,
      destChainid: BigNumberish,
      receiver: AddressLike,
      amount: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fetchOmniTokenTransferFee"
  ): TypedContractMethod<
    [destChainid: BigNumberish, receiver: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "infoBackEmit"
  ): TypedContractMethod<
    [
      earliestArrivalTimestamp: BigNumberish,
      latestArrivalTimestamp: BigNumberish,
      relayer: AddressLike,
      sender: AddressLike,
      value: BigNumberish,
      destChainid: BigNumberish,
      additionParams: BytesLike,
      message: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "maxArrivalTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxGasLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minArrivalTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minGasLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [toAddress: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mirrorToken"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receiveStandardMessage"
  ): TypedContractMethod<
    [srcChainId: BigNumberish, srcContract: BigNumberish, message: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "selectedRelayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setMirrorToken"
  ): TypedContractMethod<
    [Chainid: BigNumberish, tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "simpleBridgeMint"
  ): TypedContractMethod<
    [
      destChainId: BigNumberish,
      receiver: AddressLike,
      amount: BigNumberish,
      gasTip: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenMintfee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenOnChain"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
