/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as helperDemoSol from "./HelperDemo.sol";
export type { helperDemoSol };
import type * as orbiTokenSol from "./OrbiToken.sol";
export type { orbiTokenSol };
import type * as dAppDemoSol from "./dAppDemo.sol";
export type { dAppDemoSol };
import type * as docsSol from "./docs.sol";
export type { docsSol };
import type * as erc20DemoSol from "./erc20Demo.sol";
export type { erc20DemoSol };
export type { VizingNFT } from "./VizingNFT";
export type { MockNFT } from "./MockNFT";
