/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IMessageStruct {
  export type LandingParamsStruct = {
    messageId: BytesLike;
    earliestArrivalTimestamp: BigNumberish;
    latestArrivalTimestamp: BigNumberish;
    srcChainid: BigNumberish;
    srcTxHash: BytesLike;
    srcContract: BigNumberish;
    srcChainNonce: BigNumberish;
    sender: BigNumberish;
    value: BigNumberish;
    additionParams: BytesLike;
    message: BytesLike;
  };

  export type LandingParamsStructOutput = [
    messageId: string,
    earliestArrivalTimestamp: bigint,
    latestArrivalTimestamp: bigint,
    srcChainid: bigint,
    srcTxHash: string,
    srcContract: bigint,
    srcChainNonce: bigint,
    sender: bigint,
    value: bigint,
    additionParams: string,
    message: string
  ] & {
    messageId: string;
    earliestArrivalTimestamp: bigint;
    latestArrivalTimestamp: bigint;
    srcChainid: bigint;
    srcTxHash: string;
    srcContract: bigint;
    srcChainNonce: bigint;
    sender: bigint;
    value: bigint;
    additionParams: string;
    message: string;
  };

  export type LaunchEnhanceParamsStruct = {
    earliestArrivalTimestamp: BigNumberish;
    latestArrivalTimestamp: BigNumberish;
    relayer: AddressLike;
    sender: AddressLike;
    value: BigNumberish[];
    destChainid: BigNumberish[];
    additionParams: BytesLike[];
    message: BytesLike[];
  };

  export type LaunchEnhanceParamsStructOutput = [
    earliestArrivalTimestamp: bigint,
    latestArrivalTimestamp: bigint,
    relayer: string,
    sender: string,
    value: bigint[],
    destChainid: bigint[],
    additionParams: string[],
    message: string[]
  ] & {
    earliestArrivalTimestamp: bigint;
    latestArrivalTimestamp: bigint;
    relayer: string;
    sender: string;
    value: bigint[];
    destChainid: bigint[];
    additionParams: string[];
    message: string[];
  };
}

export interface IMessageChannelInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "Chainid"
      | "GetNonceLanding"
      | "GetNonceLaunch"
      | "Landing"
      | "LandingSpecifiedGas"
      | "Launch"
      | "Version"
      | "estimateGas(uint256[],uint64[],bytes[],bytes[])"
      | "estimateGas(uint256,uint64,bytes,bytes)"
      | "estimatePrice"
      | "expertLandingHook"
      | "expertLaunchHook"
      | "gasSystemAddr"
      | "launchMultiChain"
      | "maxArrivalTime"
      | "minArrivalTime"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "Chainid", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "GetNonceLanding",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "GetNonceLaunch",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "Landing",
    values: [IMessageStruct.LandingParamsStruct[], BytesLike[][]]
  ): string;
  encodeFunctionData(
    functionFragment: "LandingSpecifiedGas",
    values: [IMessageStruct.LandingParamsStruct[], BigNumberish, BytesLike[][]]
  ): string;
  encodeFunctionData(
    functionFragment: "Launch",
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "Version", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "estimateGas(uint256[],uint64[],bytes[],bytes[])",
    values: [BigNumberish[], BigNumberish[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateGas(uint256,uint64,bytes,bytes)",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "estimatePrice",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "expertLandingHook",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "expertLaunchHook",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gasSystemAddr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "launchMultiChain",
    values: [IMessageStruct.LaunchEnhanceParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "maxArrivalTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minArrivalTime",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "Chainid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "GetNonceLanding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GetNonceLaunch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "Landing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "LandingSpecifiedGas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "Launch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Version", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "estimateGas(uint256[],uint64[],bytes[],bytes[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateGas(uint256,uint64,bytes,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimatePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expertLandingHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expertLaunchHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gasSystemAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "launchMultiChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxArrivalTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minArrivalTime",
    data: BytesLike
  ): Result;
}

export interface IMessageChannel extends BaseContract {
  connect(runner?: ContractRunner | null): IMessageChannel;
  waitForDeployment(): Promise<this>;

  interface: IMessageChannelInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  Chainid: TypedContractMethod<[], [bigint], "view">;

  GetNonceLanding: TypedContractMethod<
    [chainId: BigNumberish, sender: AddressLike],
    [bigint],
    "view"
  >;

  GetNonceLaunch: TypedContractMethod<
    [chainId: BigNumberish, sender: AddressLike],
    [bigint],
    "view"
  >;

  Landing: TypedContractMethod<
    [params: IMessageStruct.LandingParamsStruct[], proofs: BytesLike[][]],
    [void],
    "payable"
  >;

  LandingSpecifiedGas: TypedContractMethod<
    [
      params: IMessageStruct.LandingParamsStruct[],
      gasLimit: BigNumberish,
      proofs: BytesLike[][]
    ],
    [void],
    "payable"
  >;

  Launch: TypedContractMethod<
    [
      earliestArrivalTimestamp: BigNumberish,
      latestArrivalTimestamp: BigNumberish,
      relayer: AddressLike,
      sender: AddressLike,
      value: BigNumberish,
      destChainid: BigNumberish,
      additionParams: BytesLike,
      message: BytesLike
    ],
    [void],
    "payable"
  >;

  Version: TypedContractMethod<[], [string], "view">;

  "estimateGas(uint256[],uint64[],bytes[],bytes[])": TypedContractMethod<
    [
      value: BigNumberish[],
      destChainid: BigNumberish[],
      additionParams: BytesLike[],
      message: BytesLike[]
    ],
    [bigint],
    "view"
  >;

  "estimateGas(uint256,uint64,bytes,bytes)": TypedContractMethod<
    [
      value: BigNumberish,
      destChainid: BigNumberish,
      additionParams: BytesLike,
      message: BytesLike
    ],
    [bigint],
    "view"
  >;

  estimatePrice: TypedContractMethod<
    [sender: AddressLike, destChainid: BigNumberish],
    [bigint],
    "view"
  >;

  expertLandingHook: TypedContractMethod<[hook: BytesLike], [string], "view">;

  expertLaunchHook: TypedContractMethod<[hook: BytesLike], [string], "view">;

  gasSystemAddr: TypedContractMethod<[], [string], "view">;

  launchMultiChain: TypedContractMethod<
    [params: IMessageStruct.LaunchEnhanceParamsStruct],
    [void],
    "payable"
  >;

  maxArrivalTime: TypedContractMethod<[], [bigint], "view">;

  minArrivalTime: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "Chainid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GetNonceLanding"
  ): TypedContractMethod<
    [chainId: BigNumberish, sender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "GetNonceLaunch"
  ): TypedContractMethod<
    [chainId: BigNumberish, sender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "Landing"
  ): TypedContractMethod<
    [params: IMessageStruct.LandingParamsStruct[], proofs: BytesLike[][]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "LandingSpecifiedGas"
  ): TypedContractMethod<
    [
      params: IMessageStruct.LandingParamsStruct[],
      gasLimit: BigNumberish,
      proofs: BytesLike[][]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "Launch"
  ): TypedContractMethod<
    [
      earliestArrivalTimestamp: BigNumberish,
      latestArrivalTimestamp: BigNumberish,
      relayer: AddressLike,
      sender: AddressLike,
      value: BigNumberish,
      destChainid: BigNumberish,
      additionParams: BytesLike,
      message: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "Version"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "estimateGas(uint256[],uint64[],bytes[],bytes[])"
  ): TypedContractMethod<
    [
      value: BigNumberish[],
      destChainid: BigNumberish[],
      additionParams: BytesLike[],
      message: BytesLike[]
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "estimateGas(uint256,uint64,bytes,bytes)"
  ): TypedContractMethod<
    [
      value: BigNumberish,
      destChainid: BigNumberish,
      additionParams: BytesLike,
      message: BytesLike
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "estimatePrice"
  ): TypedContractMethod<
    [sender: AddressLike, destChainid: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "expertLandingHook"
  ): TypedContractMethod<[hook: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "expertLaunchHook"
  ): TypedContractMethod<[hook: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "gasSystemAddr"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "launchMultiChain"
  ): TypedContractMethod<
    [params: IMessageStruct.LaunchEnhanceParamsStruct],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "maxArrivalTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minArrivalTime"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
